language: python
python:
  - "3.7"
before_install:
  - 'echo "slack: secret" >> secrets.yaml'
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
