- id: '1579349508168'
  alias: Storage shed temperature outside interval
  trigger:
  - below: '2'
    entity_id: sensor.forradet_temperature
    for: 00:10:00
    platform: numeric_state
  - above: '10'
    entity_id: sensor.forradet_temperature
    for: 00:10:00
    platform: numeric_state
  action:
  - service: notify.slack
    data:
      message: Temp in shed is {{states('sensor.forradet_temperature')}} {{state_attr('sensor.forradet_temperature',
        'unit_of_measurement')}}
      target:
      - '#logs'
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Temp in shed is {{states('sensor.forradet_temperature')}} {{state_attr('sensor.forradet_temperature',
        'unit_of_measurement')}}


- alias: Storage shed temperature inside interval
  trigger:
  - below: '10'
    entity_id: sensor.forradet_temperature
    for: 00:10:00
    platform: numeric_state
  - above: '2'
    entity_id: sensor.forradet_temperature
    for: 00:10:00
    platform: numeric_state
  action:
  - service: notify.slack
    data:
      message: Temp in shed is {{states('sensor.forradet_temperature')}} {{state_attr('sensor.forradet_temperature',
        'unit_of_measurement')}}
      target:
      - '#logs'
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Temp in shed is {{states('sensor.forradet_temperature')}} {{state_attr('sensor.forradet_temperature',
        'unit_of_measurement')}}

- alias: Turn on lights in common areas when the sun gets dim
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 3.5
  action:
  - service: scene.turn_on
    entity_id: scene.common_lights_on
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Turn on lights in common areas

- alias: Turn off lights in common areas when the sun gets bright
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 3.5
  action:
  - service: scene.turn_on
    entity_id: scene.common_lights_off
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Turn off lights in common areas
