- alias: Storage shed temperature outside interval
  trigger:
  - below: '2'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00
    platform: numeric_state
  - above: '10'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00 
    platform: numeric_state
  action:
  - service: notify.slack
    data:
      message: Temp in shed is {{states('sensor.temperaturehumidity_sensor_01_temperature')}} {{state_attr('sensor.temperaturehumidity_sensor_01_temperature',
        'unit_of_measurement')}}
      target:
      - '#logs'
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Temp in shed is {{states('sensor.temperaturehumidity_sensor_01_temperature')}} {{state_attr('sensor.temperaturehumidity_sensor_01_temperature',
        'unit_of_measurement')}}


- alias: Storage shed temperature inside interval
  trigger:
  - below: '10'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00
    platform: numeric_state
  - above: '2'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00
    platform: numeric_state
  action:
  - service: notify.slack
    data:
      message: Temp in shed is {{states('sensor.temperaturehumidity_sensor_01_temperature')}} {{state_attr('sensor.temperaturehumidity_sensor_01_temperature',
        'unit_of_measurement')}}
      target:
      - '#logs'
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Temp in shed is {{states('sensor.temperaturehumidity_sensor_01_temperature')}} {{state_attr('sensor.temperaturehumidity_sensor_01_temperature',
        'unit_of_measurement')}}

- alias: Turn on lights when the sun gets dim
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 3.5
  action:
  - service: switch.turn_on
    entity_id: switch.plug_02
  - service: scene.turn_on
    entity_id: scene.common_lights_on
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Sun is dim, turn on lights

- alias: Turn off lights when the sun gets bright
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 3.5
  action:
  - service: switch.turn_off
    entity_id: switch.plug_02
  - service: scene.turn_on
    entity_id: scene.common_lights_off
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Sun is bright, turn off lights

- alias: Turn on common lights in morning
  trigger:
    platform: time
    at: "07:00:00"
  action:
  - service: scene.turn_on
    entity_id: scene.common_lights_on

- alias: Turn off common lights at bedtime
  trigger:
    platform: time
    at: "21:00:00"
  action:
  - service: scene.turn_off
    entity_id: scene.common_lights_off
