- alias: 'Turn off idle bike charger'
  trigger:
    - platform: numeric_state
      value_template: '{{ state.attributes.power|default(0)|int }}'
      entity_id: sensor.power_22
      below: 10
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.smart_plug_6
