- alias: 'Turn off idle bike charger'
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_22
      below: '20'
  action:
    - service: switch.turn_off
      entity_id: switch.smart_plug_6
