- alias: 'Turn off idle bike charger'
  id: 'turn-off-idle-bike-charger'
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_22
      below: 800
      for:
        hours: 0
        minutes: 0
        seconds: 1
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.smart_plug_6
    - service: notify.mobile_app_erik_iphone_13_mini
      data:
        message: "Your message goes here"
        title: "Custom subject"
