###############################################################################
## States
###############################################################################
- alias: 'Fridge on state'
  id: 'fridge on state'
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_20
      above: 10
  condition:
    - condition: state
      entity_id: input_boolean.fridge_on
      state: 'off'
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.fridge_on

- alias: 'Fridge off state'
  id: 'fridge off state'
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_20
      below: 10
  condition:
    - condition: state
      entity_id: input_boolean.fridge_on
      state: 'on'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.fridge_on

###############################################################################
## Actions
###############################################################################
- alias: 'Notify when fridge turned off'
  id: 'notify when fridge turned off'
  trigger:
    - platform: state
      entity_id: input_boolean.fridge_on
      to: 'off'
  action:
    - service: notify.mobile_app_erik_iphone_13_mini
      data:
        title: "Fridge"
        message: "Turned off"

- alias: 'Attempt turn on fridge when off for one minute'
  id: 'attempt turn on fridge when off for one minute'
  trigger:
    - platform: state
      entity_id: input_boolean.fridge_on
      to: 'off'
  action:
    - service: switch.turn_on
      target:
          entity_id: switch.smart_plug_5
      data:
        title: "Fridge"
        message: "Turned off"

