###############################################################################
## Actions
###############################################################################
- alias: 'Increase heat pump fan speed during office hours'
  id: 'increase heat pump fan speed during office hours'
  trigger:
    - platform: time_pattern
      minutes: '/15'
  condition:
    - condition: state
      entity_id: input_boolean.office_hours_active
      state: 'on'
    - condition: state
      entity_id: climate.luftvarmepump
      state: 'cool'
    - condition: state
      entity_id: weather.smhi_home
      state: 'sunny'
  action:
    - service: climate.set_fan_mode
      data:
        fan_mode: '5'
        entity_id: 'climate.luftvarmepump'
    - service: climate.set_swing_mode
      data:
        swing_mode: '5_down'
        entity_id: 'climate.luftvarmepump'

- alias: 'Decrease heat pump fan speed outside office hours'
  id: 'decrease heat pump fan speed outside office hours'
  trigger:
    - platform: state
      entity_id: input_boolean.office_hours_active
      to: 'off'
  condition:
    - condition: state
      entity_id: climate.luftvarmepump
      state: 'cool'
  action:
    - service: climate.set_fan_mode
      data:
        fan_mode: 'auto'
        entity_id: 'climate.luftvarmepump'
    - service: climate.set_swing_mode
      data:
        swing_mode: '1_up'
        entity_id: 'climate.luftvarmepump'

