###############################################################################
## office hours
###############################################################################
- alias: 'Time of day in office hours state'
  id: 'time of day in office hours state'
  trigger:
    - platform: time
      at: '08:00:00'
      id: '08'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.office_hours_active

- alias: 'Time of day outside office hours state'
  id: 'time of day outside office hours state'
  trigger:
    - platform: time
      at: '16:00:00'
      id: '16'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.office_hours_active

###############################################################################
## night time
###############################################################################
- alias: 'Time of day night time'
  id: 'time of day in night time'
  trigger:
    - platform: time
      at: '22:00:00'
      id: '22'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.night_time_active

- alias: 'Time of day not night time'
  id: 'time of day not night time'
  trigger:
    - platform: time
      at: '06:00:00'
      id: '06'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night_time_active

