###############################################################################
## night time
###############################################################################
- alias: 'Evening starts'
  id: 'evening starts'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition: and
  conditions:
     - condition: time
       before: "21:00:00"
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
         - sat
         - sun
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.common_lights
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kids_lights
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.outdoor_lights

- alias: 'Kids evening ends'
  id: 'kids evening ends'
  trigger:
    platform: time
    at: "21:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kids_lights


- alias: 'Evening ends'
  id: 'evening ends'
  trigger:
    platform: time
    at: "22:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.common_lights

- alias: 'Weekday morning start'
  id: 'weekday morning starts'
  trigger:
    - platform: time
      at: '06:20:00'
      id: '06'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.common_lights

- alias: 'Weekend morning start'
  id: 'weekend morning start'
  trigger:
    - platform: time
      at: '07:20:00'
      id: '06'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.common_lights

- alias: 'Morning ends'
  id: 'morning ends'
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.common_lights
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.outdoor_lights

