- alias: Turn on common lights in morning
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    condition: sun
    before: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.common_lights_on

- alias: Turn off lights when the sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: switch.turn_off
      entity_id: switch.smart_plug_2
    - service: switch.turn_off
      entity_id: switch.smart_plug_4
    - service: switch.turn_off
      entity_id: switch.plug_02

- alias: Turn on lights when the sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: time
    before: "21:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.plug_02
    - service: switch.turn_on
      entity_id: switch.plug_04
    - service: scene.turn_on
      entity_id: scene.common_lights_on
    - service: switch.turn_on
      entity_id: switch.smart_plug_6
    - service: scene.turn_on
      entity_id: scene.outdoor_lights_on

- alias: Turn off lights at bedtime
  trigger:
    platform: time
    at: "21:15:00"
  action:
    - service: switch.turn_off
      entity_id: switch.smart_plug_6
    - service: scene.turn_on
      entity_id: scene.common_lights_off

- alias: Turn off outdoor lights at late
  trigger:
    platform: time
    at: "23:00:00"
  action:
    - service: scene.turn_on
      entity_id: scene.outdoor_lights_off

- alias: Turn on living room lights for early birds
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    from: "off"
    to: "on"
  condition:
    condition: sun
    before: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.common_lights_on
