- alias: Turn on common lights in morning
  trigger:
    platform: time
    at: "06:30:00"
  condition:
    condition: sun
    before: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.common_lights_on

- alias: Turn off lights when the sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.outdoor_lights_off
    - service: scene.turn_on
      entity_id: scene.common_lights_off

- alias: Turn on lights when the sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: time
    before: "21:00:00"
  action:
    - service: scene.turn_on
      entity_id: scene.common_lights_on
    - service: scene.turn_on
      entity_id: scene.outdoor_lights_on

- alias: Turn on the kids' lights at bedtime
  trigger:
    platform: time
    at: "18:30:00"
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - service: scene.turn_on
      entity_id: scene.kids_lights_on

- alias: Turn off the kids' lights at late
  trigger:
    platform: time
    at: "20:00:00"
  action:
    - service: scene.turn_on
      entity_id: scene.kids_lights_off

- alias: Turn off lights at bedtime
  trigger:
    platform: time
    at: "23:00:00"
  action:
    - service: scene.turn_on
      entity_id: scene.common_lights_off

- alias: Turn on living room lights for early birds
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    from: "off"
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "05:00:00"
      - condition: sun
        before: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.common_lights_on
