- alias: Storage shed temperature outside interval
  trigger:
  - below: '2'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00
    platform: numeric_state
  - above: '10'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00 
    platform: numeric_state
  action:
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Temp in shed is outside interval {{states('sensor.temperaturehumidity_sensor_01_temperature')}} {{state_attr('sensor.temperaturehumidity_sensor_01_temperature',
        'unit_of_measurement')}}

- alias: Storage shed temperature inside interval
  trigger:
  - below: '10'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00
    platform: numeric_state
  - above: '2'
    entity_id: sensor.temperaturehumidity_sensor_01_temperature
    for: 00:10:00
    platform: numeric_state
  action:
  - service: notify.mobile_app_eriks_iphone
    data:
      message: Temp in shed is restored