###############################################################################
## States
###############################################################################
- alias: 'Time of day in office hours state'
  id: 'time of day in office hours state'
  trigger:
    - platform: time
      at: '08:00:00'
      id: '08'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.office_hours_active

- alias: 'Time of day outside office hours state'
  id: 'time of day outside office hours state'
  trigger:
    - platform: time
      at: '16:00:00'
      id: '16'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.office_hours_active

