- alias: 'Turn off idle bike charger'
  id: 'turn off idle bike charger'
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_22
      below: 20
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.smart_plug_6
    - service: notify.mobile_app_erik_iphone_13_mini
      data:
        title: "Bike battery"
        message: "Charged"


