###############################################################################
## States
###############################################################################
- alias: 'Storage temperature too low'
  id: 'storage temperature too low'
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_3
      below: 1
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.storage_temperature_too_low

- alias: 'Storage temperature ok'
  id: 'storage temperature ok'
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_3
      above: 6
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.storage_temperature_too_low

###############################################################################
## Actions
###############################################################################
- alias: 'Notify when storage temperature too low'
  id:  'notify when storage temperature too low'
  trigger:
    - platform: state
      entity_id: input_boolean.storage_temperature_too_low
      to: 'on'
  action:
    - service: notify.mobile_app_erik_iphone_13_mini
      data:
        title: "Storage temperature"
        message: "Too low"

- alias: 'Turn on element when temperature too low'
  id: 'turn on element when temperature too low'
  trigger:
    - platform: state
      entity_id: input_boolean.storage_temperature_too_low
      to: 'on'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.on_off_plug_in_unit_12

- alias: 'Notify when storage temperature ok'
  id: 'notify when storage temperature ok'
  trigger:
    - platform: state
      entity_id: input_boolean.storage_temperature_too_low
      to: 'off'
  action:
    - service: notify.mobile_app_erik_iphone_13_mini
      data:
        title: "Storage temperature"
        message: "Ok"

- alias: 'Turn off element when temperature ok'
  id: 'turn off element when temperature ok'
  trigger:
    - platform: state
      entity_id: input_boolean.storage_temperature_too_low
      to: 'off'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.on_off_plug_in_unit_12


